apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  namespace: targeting-service
  labels:
    app: targeting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: targeting-service
  template:
    metadata:
      labels:
        app: targeting-service
    spec:
      containers:
        - name: targeting-service
          image: REPLACE_ME_TARGETING_SERVICE_IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8003
          envFrom:
            - configMapRef:
                name: targeting-service-config
