prefix       = "terraform"
project      = "eks-setup"
environment  = "dev"
aws_region   = "us-east-1"
cluster_name = "eks-cluster"
# Obrigatorio
cidr_block         = "10.0.0.0/16"
argocd_domain      = "argocd.jhousyfran.click"
route53_zone_id    = "Z07819523R9W5PAE1QMAH"
argocd_server_addr = "https://argocd.jhousyfran.click"
argocd_auth_token  = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJ0ZXJyYWZvcm06YXBpS2V5IiwibmJmIjoxNzc0Mzg5OTU4LCJpYXQiOjE3NzQzODk5NTgsImp0aSI6IjNlNWY2MjdiLTkzNGQtNDkzOS1hYmE4LWQ4MjY0YjJmMTEzYyJ9.4hBqagETHUFl7wiLzueQXRDvRSMMdylYYXHZuFJ9r7o"
argocd_repo_url    = "https://github.com/Jhousyfran/pos-desafio-2"
apps_domain        = "desafio.jhousyfran.click"
