apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
  namespace: flag-service
  labels:
    app: flag-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flag-service
  template:
    metadata:
      labels:
        app: flag-service
    spec:
      containers:
        - name: flag-service
          image: REPLACE_ME_FLAG_SERVICE_IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: flag-service-config
